use std::process::Command;

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = std::path::Path::new(&out_dir);

    // Assemble pvm.s (the canonical COR24 p-code VM) with cor24-emulator's
    // assembler at build time. This guarantees we run the exact same VM
    // the CLI uses; no hand-ported opcode table to drift.
    let pvm_src = std::fs::read_to_string("asm/pvm.s").expect("asm/pvm.s");
    let mut asm = cor24_emulator::Assembler::new();
    let result = asm.assemble(&pvm_src);
    if !result.errors.is_empty() {
        for e in &result.errors {
            eprintln!("pvm.s: {e}");
        }
        panic!("pvm.s assembly failed");
    }
    std::fs::write(out_path.join("pvm.bin"), &result.bytes).unwrap();

    // Capture the labels the runner needs at runtime. `code_ptr` is the
    // memory location pvm.s reads at boot to discover where the loaded
    // p-code image lives — patching it to 0x010000 makes pvm pick up our
    // ocaml.p24m image and walk its multi-unit header automatically.
    let labels = ["code_ptr", "vm_state", "vm_loop", "code_seg", "vm_flags"];
    let mut labels_rs = String::from("// Generated by build.rs — do not edit\n");
    labels_rs.push_str("pub const PVM_LABELS: &[(&str, u32)] = &[\n");
    for name in &labels {
        let addr = result.labels.get(*name).copied().unwrap_or(0);
        labels_rs.push_str(&format!("    (\"{name}\", 0x{addr:06X}),\n"));
    }
    labels_rs.push_str("];\n");
    std::fs::write(out_path.join("pvm_labels.rs"), labels_rs).unwrap();
    println!("cargo:rerun-if-changed=asm/pvm.s");

    // Vendor the linked OCaml interpreter image (header parsed at runtime
    // by pvm.s, not by us — we just hand it the bytes).
    let ocaml_p24m = std::fs::read("assets/ocaml.p24m").expect("assets/ocaml.p24m");
    std::fs::write(out_path.join("ocaml.p24m"), &ocaml_p24m).unwrap();
    println!("cargo:rerun-if-changed=assets/ocaml.p24m");

    let sha = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    let host = Command::new("hostname")
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    let timestamp = Command::new("date")
        .args(["-u", "+%Y-%m-%dT%H:%M:%SZ"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".into());

    println!("cargo:rustc-env=BUILD_SHA={sha}");
    println!("cargo:rustc-env=BUILD_HOST={host}");
    println!("cargo:rustc-env=BUILD_TIMESTAMP={timestamp}");
}
